use_default_settings:
  engines:
    keep_only:
      - bing
      - bing images
      - bing news
      - bing videos
      - baidu
      - sogou
      - sogou images
      - sogou videos
      - sogou wechat
      - yandex

general:
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json

server:
  secret_key: "change-this-secret"
  limiter: false
  image_proxy: false
  public_instance: false
  method: "GET"
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false

# Enable engines that are accessible from mainland China
engines:
  - name: bing
    disabled: false
  - name: baidu
    disabled: false
  - name: sogou
    disabled: false
  - name: sogou images
    disabled: false
  - name: sogou videos
    disabled: false
  - name: sogou wechat
    disabled: false
  - name: yandex
    disabled: false
