from datetime import time

BEIJING_TIMEZONE = "Asia/Shanghai"
BEIJING_TIME_FORMAT = "%Y-%m-%d %H:%M"
PRIORITY_ABSOLUTE = 65_536

WAKE_WORDS = {"起床", "早安", "醒了", "睡醒了", "起了", "苏醒"}
SLEEP_WORDS = {"晚安", "睡觉", "睡了", "睡啦", "困了", "眠了"}

WAKE_TARGET = time(7, 30)
SLEEP_TARGET = time(23, 30)

RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_RULES = {
    "timezone_wake": {"global_limit": 3, "user_limit": 1},
    "timezone_sleep": {"global_limit": 3, "user_limit": 1},
    "divine_arrival": {"global_limit": 6, "user_limit": 3},
    "play_target": {"global_limit": 6, "user_limit": 3},
    "double_char_ni_de": {"global_limit": 6, "user_limit": 3},
    "sandwich_de": {"global_limit": 6, "user_limit": 3},
    "like_reply": {"global_limit": 6, "user_limit": 3},
    "repeat_follow_read": {"global_limit": 8, "user_limit": 3},
    "repeat_trim_last": {"global_limit": 8, "user_limit": 3},
    "repeat_same_user_warning": {"global_limit": 4, "user_limit": 2},
    "good_girl_chain_entry": {"global_limit": 20, "user_limit": 10},
}

I_DO_BLOCKED_VERBS = {
    "不会",
    "不能",
    "不要",
    "以为",
    "支持",
    "反对",
    "同意",
    "喜欢",
    "回去",
    "回家",
    "害怕",
    "希望",
    "忘了",
    "忘记",
    "担心",
    "明白",
    "来了",
    "知道",
    "觉得",
    "认为",
    "记得",
    "认识",
    "说过",
    "谢谢",
    "输了",
    "赢了",
}

TEXT_REPLY_RULES = [
    {
        "name": "divine_arrival",
        "patterns": [r"神临", r"降临"],
        "reply_template": "{current_time}，@{sender_name} 区从天降",
        "rate_limit_key": "divine_arrival",
        "priority": 100,
    },
    {
        "name": "play_target",
        "patterns": [r"玩(?P<target>.+?)玩的"],
        "reply_template": "{target}怎么你了",
        "rate_limit_key": "play_target",
        "priority": 85,
    },
    {
        "name": "double_char_ni_de",
        "patterns": [r"^([\u4e00-\u9fa5])(\1)你的$"],
        "reply_template": "$1牛魔",
        "rate_limit_key": "double_char_ni_de",
        "priority": 80,
    },
    {
        "name": "sandwich_de",
        "patterns": [r"^([\u4e00-\u9fa5])(.{2,})\1的$"],
        "reply_template": "$2怎么你了！",
        "rate_limit_key": "sandwich_de",
        "priority": 75,
    },
    {
        "name": "like_reply",
        "patterns": [r"^我喜欢(.+)$", r"^喜欢(.+)$"],
        "reply_template": "还在$1",
        "rate_limit_key": "like_reply",
        "priority": 60,
    },
    # These variants intentionally share one bucket so adjacent meme triggers do not spam.
    {
        "name": "maggot_arrival",
        "patterns": [r"区临", r"区来了"],
        "reply_template": "{current_time}，有自知之明的@{sender_name} 区从天降",
        "rate_limit_key": "divine_arrival",
        "priority": 95,
    },
    {
        "name": "genshin_start",
        "patterns": [r"^(.+?)[，,]\s*启动[！!]*$"],
        "reply_template": "该启动$1了，少爷",
        "rate_limit_key": "divine_arrival",
        "priority": 90,
    },
    {
        "name": "master_protection",
        "patterns": [r"四区", r"4区", r"四出", r"4出"],
        "reply_template": "你不许说他他是我跌",
        "rate_limit_key": "divine_arrival",
        "priority": PRIORITY_ABSOLUTE,
    },
    {
        "name": "huaizhen_oversize",
        "patterns": [r"怀真", r"赵怀真"],
        "reply_template": "赵怀真还不超标啊",
        "rate_limit_key": "timezone_wake",
        "priority": 50,
    },
    {
        "name": "kpl_final",
        "patterns": [r"^(.+?)尽力[，,]\s*(.+?)犯罪[，,]\s*(.+?)(?:的)?(.{2})不团队$"],
        "reply_template": "我说$1才是最大的一条区有没有懂的",
        "rate_limit_key": "divine_arrival",
        "priority": 200,
    },
    {
        "name": "i_do",
        "patterns": [r"^我(?P<verb>[\u4e00-\u9fa5]{2})[！!。，,？?]*$"],
        "blocked_named_groups": {"verb": sorted(I_DO_BLOCKED_VERBS)},
        "reply_template": "不准$1",
        "rate_limit_key": "divine_arrival",
        "priority": 20,
    }
]

REGION_ZH = {
    "Africa": "非洲",
    "America": "美洲",
    "Antarctica": "南极洲",
    "Arctic": "北极",
    "Asia": "亚洲",
    "Atlantic": "大西洋",
    "Australia": "澳洲",
    "Europe": "欧洲",
    "Indian": "印度洋",
    "Pacific": "太平洋",
}

TZ_PART_ZH = {
    "Abu_Dhabi": "阿布扎比",
    "Almaty": "阿拉木图",
    "Amman": "安曼",
    "Anadyr": "阿纳德尔",
    "Aqtau": "阿克套",
    "Aqtobe": "阿克托别",
    "Ashgabat": "阿什哈巴德",
    "Astana": "阿斯塔纳",
    "Athens": "雅典",
    "Azores": "亚速尔群岛",
    "Baghdad": "巴格达",
    "Baku": "巴库",
    "Bangkok": "曼谷",
    "Beirut": "贝鲁特",
    "Belgrade": "贝尔格莱德",
    "Bishkek": "比什凯克",
    "Brisbane": "布里斯班",
    "Calcutta": "加尔各答",
    "Cape_Verde": "佛得角",
    "Chita": "赤塔",
    "Cocos": "科科斯群岛",
    "Colombo": "科伦坡",
    "Damascus": "大马士革",
    "Dhaka": "达卡",
    "Dili": "帝力",
    "Dubai": "迪拜",
    "Dushanbe": "杜尚别",
    "Famagusta": "法马古斯塔",
    "Gaza": "加沙",
    "Godthab": "戈特霍布",
    "Hebron": "希伯伦",
    "Ho_Chi_Minh": "胡志明市",
    "Hong_Kong": "香港",
    "Irkutsk": "伊尔库茨克",
    "Istanbul": "伊斯坦布尔",
    "Jakarta": "雅加达",
    "Jerusalem": "耶路撒冷",
    "Kabul": "喀布尔",
    "Kamchatka": "堪察加",
    "Karachi": "卡拉奇",
    "Kathmandu": "加德满都",
    "Khandyga": "汉德加",
    "Kolkata": "加尔各答",
    "Krasnoyarsk": "克拉斯诺亚尔斯克",
    "Kuala_Lumpur": "吉隆坡",
    "Kuching": "古晋",
    "Macau": "澳门",
    "Magadan": "马加丹",
    "Manila": "马尼拉",
    "Miquelon": "密克隆",
    "Muscat": "马斯喀特",
    "Noronha": "费尔南多-迪诺罗尼亚",
    "Novokuznetsk": "新库兹涅茨克",
    "Novosibirsk": "新西伯利亚",
    "Omsk": "鄂木斯克",
    "Phnom_Penh": "金边",
    "Pontianak": "坤甸",
    "Pyongyang": "平壤",
    "Qatar": "卡塔尔",
    "Qostanay": "库斯塔奈",
    "Qyzylorda": "克孜勒奥尔达",
    "Rangoon": "仰光",
    "Riyadh": "利雅得",
    "Sakhalin": "萨哈林",
    "Samarkand": "撒马尔罕",
    "Seoul": "首尔",
    "Shanghai": "上海",
    "Singapore": "新加坡",
    "Srednekolymsk": "中科雷姆斯克",
    "Taipei": "台北",
    "Tashkent": "塔什干",
    "Tbilisi": "第比利斯",
    "Tehran": "德黑兰",
    "Thimphu": "廷布",
    "Tokyo": "东京",
    "Tomsk": "托木斯克",
    "Ulaanbaatar": "乌兰巴托",
    "Urumqi": "乌鲁木齐",
    "Vladivostok": "符拉迪沃斯托克",
    "Yakutsk": "雅库茨克",
    "Yangon": "仰光",
    "Yekaterinburg": "叶卡捷琳堡",
    "Yerevan": "埃里温",
}
