from datetime import time

BEIJING_TIMEZONE = "Asia/Shanghai"
BEIJING_TIME_FORMAT = "%Y-%m-%d %H:%M"
PRIORITY_ABSOLUTE = 65_536

WAKE_WORDS = {"起床", "早安", "醒了", "睡醒了", "起了", "苏醒"}
SLEEP_WORDS = {"晚安", "睡觉", "睡了", "睡啦", "困了", "眠了"}

WAKE_TARGET = time(7, 30)
SLEEP_TARGET = time(23, 30)

RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_RULES = {
    "timezone_wake": {"global_limit": 3, "user_limit": 1},
    "timezone_sleep": {"global_limit": 3, "user_limit": 1},
    "llm_chat": {"global_limit": 6, "user_limit": 3},
    "tieba_random_post": {"global_limit": 2, "user_limit": 1},
    "web_search": {"global_limit": 6, "user_limit": 3},
    "tavily_search": {"global_limit": 6, "user_limit": 3},
    "divine_arrival": {"global_limit": 6, "user_limit": 3},
    "play_target": {"global_limit": 6, "user_limit": 3},
    "double_char_ni_de": {"global_limit": 6, "user_limit": 3},
    "sandwich_de": {"global_limit": 6, "user_limit": 3},
    "like_reply": {"global_limit": 6, "user_limit": 3},
    "repeat_follow_read": {"global_limit": 8, "user_limit": 3},
    "repeat_trim_last": {"global_limit": 8, "user_limit": 3},
    "repeat_same_user_warning": {"global_limit": 4, "user_limit": 2},
    "good_girl_chain_entry": {"global_limit": 20, "user_limit": 10},
}

I_DO_BLOCKED_VERBS = {
    "不会",
    "不能",
    "不要",
    "以为",
    "支持",
    "反对",
    "同意",
    "喜欢",
    "回去",
    "回家",
    "害怕",
    "希望",
    "忘了",
    "忘记",
    "担心",
    "明白",
    "来了",
    "知道",
    "觉得",
    "认为",
    "记得",
    "认识",
    "说过",
    "谢谢",
    "输了",
    "赢了",
}

TEXT_REPLY_RULES = [
    {
        "name": "divine_arrival",
        "patterns": [r"神临", r"降临"],
        "reply_template": "{current_time}，@{sender_name} 区从天降",
        "rate_limit_key": "divine_arrival",
        "priority": 100,
    },
    {
        "name": "play_target",
        "patterns": [r"玩(?P<target>.+?)玩的"],
        "reply_template": "{target}怎么你了",
        "rate_limit_key": "play_target",
        "priority": 85,
    },
    {
        "name": "double_char_ni_de",
        "patterns": [r"^([\u4e00-\u9fa5])(\1)你的$"],
        "reply_template": "$1牛魔",
        "rate_limit_key": "double_char_ni_de",
        "priority": 80,
    },
    {
        "name": "sandwich_de",
        "patterns": [r"^([\u4e00-\u9fa5])(.{2,})\1的$"],
        "reply_template": "$2怎么你了！",
        "rate_limit_key": "sandwich_de",
        "priority": 75,
    },
    {
        "name": "like_reply",
        "patterns": [r"^我喜欢(.+)$", r"^喜欢(.+)$"],
        "reply_template": "还在$1",
        "rate_limit_key": "like_reply",
        "priority": 60,
    },
    # These variants intentionally share one bucket so adjacent meme triggers do not spam.
    {
        "name": "maggot_arrival",
        "patterns": [r"区临", r"区来了"],
        "reply_template": "{current_time}，有自知之明的@{sender_name} 区从天降",
        "rate_limit_key": "divine_arrival",
        "priority": 95,
    },
    {
        "name": "genshin_start",
        "patterns": [r"^(.+?)[，,]\s*启动[！!]*$"],
        "reply_template": "该启动$1了，少爷",
        "rate_limit_key": "divine_arrival",
        "priority": 90,
    },
    {
        "name": "master_protection",
        "patterns": [r"四区", r"4区", r"四出", r"4出"],
        "reply_template": "你不许说他他是我跌",
        "rate_limit_key": "divine_arrival",
        "priority": PRIORITY_ABSOLUTE,
    },
    {
        "name": "huaizhen_oversize",
        "patterns": [r"怀真", r"赵怀真"],
        "reply_template": "赵怀真还不超标啊",
        "rate_limit_key": "timezone_wake",
        "priority": 50,
    },
    {
        "name": "kpl_final",
        "patterns": [r"^(.+?)尽力[，,]\s*(.+?)犯罪[，,]\s*(.+?)(?:的)?(.{2})不团队$"],
        "reply_template": "我说$1才是最大的一条区有没有懂的",
        "rate_limit_key": "divine_arrival",
        "priority": 200,
    },
    {
        "name": "i_do",
        "patterns": [r"^我(?P<verb>[\u4e00-\u9fa5]{2})[！!。，,？?]*$"],
        "blocked_named_groups": {"verb": sorted(I_DO_BLOCKED_VERBS)},
        "reply_template": "不准$1",
        "rate_limit_key": "divine_arrival",
        "priority": 20,
    }
]

SCHEDULED_MESSAGES: list[dict] = []
# Example entry (uncomment and fill in to enable):
# SCHEDULED_MESSAGES = [
#     {"cron": "0 7 * * *", "group_ids": [123456], "message": "早上好！"},
# ]

REGION_ZH = {
    "Africa": "非洲",
    "America": "美洲",
    "Antarctica": "南极洲",
    "Arctic": "北极",
    "Asia": "亚洲",
    "Atlantic": "大西洋",
    "Australia": "澳洲",
    "Europe": "欧洲",
    "Indian": "印度洋",
    "Pacific": "太平洋",
}

TZ_PART_ZH = {
    # ── 亚洲 ──
    "Abu_Dhabi": "阿布扎比",
    "Almaty": "阿拉木图",
    "Amman": "安曼",
    "Ashgabat": "阿什哈巴德",
    "Ashkhabad": "阿什哈巴德",
    "Astana": "阿斯塔纳",
    "Atyrau": "阿特劳",
    "Baghdad": "巴格达",
    "Bahrain": "巴林",
    "Baku": "巴库",
    "Bangkok": "曼谷",
    "Barnaul": "巴尔瑙尔",
    "Beirut": "贝鲁特",
    "Bishkek": "比什凯克",
    "Brunei": "文莱",
    "Calcutta": "加尔各答",
    "Choibalsan": "乔巴山",
    "Chongqing": "重庆",
    "Chungking": "重庆",
    "Colombo": "科伦坡",
    "Damascus": "大马士革",
    "Dhaka": "达卡",
    "Dacca": "达卡",
    "Dubai": "迪拜",
    "Dushanbe": "杜尚别",
    "Gaza": "加沙",
    "Harbin": "哈尔滨",
    "Hebron": "希伯伦",
    "Ho_Chi_Minh": "胡志明市",
    "Hong_Kong": "香港",
    "Hovd": "科布多",
    "Irkutsk": "伊尔库茨克",
    "Istanbul": "伊斯坦布尔",
    "Jakarta": "雅加达",
    "Jayapura": "查亚普拉",
    "Jerusalem": "耶路撒冷",
    "Kabul": "喀布尔",
    "Kamchatka": "堪察加",
    "Karachi": "卡拉奇",
    "Kashgar": "喀什",
    "Kathmandu": "加德满都",
    "Katmandu": "加德满都",
    "Kolkata": "加尔各答",
    "Krasnoyarsk": "克拉斯诺亚尔斯克",
    "Kuala_Lumpur": "吉隆坡",
    "Kuwait": "科威特",
    "Macau": "澳门",
    "Macao": "澳门",
    "Magadan": "马加丹",
    "Makassar": "望加锡",
    "Manila": "马尼拉",
    "Muscat": "马斯喀特",
    "Nicosia": "尼科西亚",
    "Novosibirsk": "新西伯利亚",
    "Omsk": "鄂木斯克",
    "Oral": "乌拉尔",
    "Phnom_Penh": "金边",
    "Pyongyang": "平壤",
    "Qatar": "卡塔尔",
    "Rangoon": "仰光",
    "Riyadh": "利雅得",
    "Saigon": "胡志明市",
    "Sakhalin": "萨哈林",
    "Samarkand": "撒马尔罕",
    "Seoul": "首尔",
    "Shanghai": "上海",
    "Singapore": "新加坡",
    "Taipei": "台北",
    "Tashkent": "塔什干",
    "Tbilisi": "第比利斯",
    "Tehran": "德黑兰",
    "Tel_Aviv": "特拉维夫",
    "Thimphu": "廷布",
    "Thimbu": "廷布",
    "Tokyo": "东京",
    "Tomsk": "托木斯克",
    "Ujung_Pandang": "望加锡",
    "Ulaanbaatar": "乌兰巴托",
    "Ulan_Bator": "乌兰巴托",
    "Urumqi": "乌鲁木齐",
    "Vientiane": "万象",
    "Vladivostok": "符拉迪沃斯托克",
    "Yakutsk": "雅库茨克",
    "Yangon": "仰光",
    "Yekaterinburg": "叶卡捷琳堡",
    "Yerevan": "埃里温",
    # ── 欧洲 ──
    "Amsterdam": "阿姆斯特丹",
    "Andorra": "安道尔",
    "Astrakhan": "阿斯特拉罕",
    "Athens": "雅典",
    "Belgrade": "贝尔格莱德",
    "Berlin": "柏林",
    "Bratislava": "布拉迪斯拉发",
    "Brussels": "布鲁塞尔",
    "Bucharest": "布加勒斯特",
    "Budapest": "布达佩斯",
    "Chisinau": "基希讷乌",
    "Copenhagen": "哥本哈根",
    "Dublin": "都柏林",
    "Gibraltar": "直布罗陀",
    "Helsinki": "赫尔辛基",
    "Kaliningrad": "加里宁格勒",
    "Kiev": "基辅",
    "Kirov": "基洛夫",
    "Kyiv": "基辅",
    "Lisbon": "里斯本",
    "Ljubljana": "卢布尔雅那",
    "London": "伦敦",
    "Luxembourg": "卢森堡",
    "Madrid": "马德里",
    "Malta": "马耳他",
    "Minsk": "明斯克",
    "Monaco": "摩纳哥",
    "Moscow": "莫斯科",
    "Oslo": "奥斯陆",
    "Paris": "巴黎",
    "Prague": "布拉格",
    "Riga": "里加",
    "Rome": "罗马",
    "Samara": "萨马拉",
    "Sarajevo": "萨拉热窝",
    "Saratov": "萨拉托夫",
    "Simferopol": "辛菲罗波尔",
    "Skopje": "斯科普里",
    "Sofia": "索菲亚",
    "Stockholm": "斯德哥尔摩",
    "Tallinn": "塔林",
    "Tirane": "地拉那",
    "Ulyanovsk": "乌里扬诺夫斯克",
    "Vienna": "维也纳",
    "Vilnius": "维尔纽斯",
    "Volgograd": "伏尔加格勒",
    "Warsaw": "华沙",
    "Zagreb": "萨格勒布",
    "Zurich": "苏黎世",
    # ── 非洲 ──
    "Abidjan": "阿比让",
    "Accra": "阿克拉",
    "Addis_Ababa": "亚的斯亚贝巴",
    "Algiers": "阿尔及尔",
    "Cairo": "开罗",
    "Casablanca": "卡萨布兰卡",
    "Dar_es_Salaam": "达累斯萨拉姆",
    "Djibouti": "吉布提",
    "Harare": "哈拉雷",
    "Johannesburg": "约翰内斯堡",
    "Kampala": "坎帕拉",
    "Khartoum": "喀土穆",
    "Kinshasa": "金沙萨",
    "Lagos": "拉各斯",
    "Maputo": "马普托",
    "Mogadishu": "摩加迪沙",
    "Nairobi": "内罗毕",
    "Tripoli": "的黎波里",
    "Tunis": "突尼斯",
    "Windhoek": "温得和克",
    # ── 美洲 ──
    "Anchorage": "安克雷奇",
    "Argentina": "阿根廷",
    "Bogota": "波哥大",
    "Buenos_Aires": "布宜诺斯艾利斯",
    "Caracas": "加拉加斯",
    "Chicago": "芝加哥",
    "Denver": "丹佛",
    "Edmonton": "埃德蒙顿",
    "Guayaquil": "瓜亚基尔",
    "Halifax": "哈利法克斯",
    "Havana": "哈瓦那",
    "La_Paz": "拉巴斯",
    "Lima": "利马",
    "Los_Angeles": "洛杉矶",
    "Managua": "马那瓜",
    "Manaus": "马瑙斯",
    "Mexico_City": "墨西哥城",
    "Montevideo": "蒙得维的亚",
    "Montreal": "蒙特利尔",
    "New_York": "纽约",
    "Nuuk": "努克",
    "Panama": "巴拿马",
    "Phoenix": "凤凰城",
    "Puerto_Rico": "波多黎各",
    "Santiago": "圣地亚哥",
    "Santo_Domingo": "圣多明各",
    "Sao_Paulo": "圣保罗",
    "Toronto": "多伦多",
    "Vancouver": "温哥华",
    "Winnipeg": "温尼伯",
    # ── 大洋洲 / 太平洋 ──
    "Adelaide": "阿德莱德",
    "Apia": "阿皮亚",
    "Auckland": "奥克兰",
    "Brisbane": "布里斯班",
    "Darwin": "达尔文",
    "Fiji": "斐济",
    "Guam": "关岛",
    "Honolulu": "檀香山",
    "Melbourne": "墨尔本",
    "Norfolk": "诺福克岛",
    "Noumea": "努美阿",
    "Pago_Pago": "帕果帕果",
    "Perth": "珀斯",
    "Port_Moresby": "莫尔兹比港",
    "Sydney": "悉尼",
    "Tongatapu": "汤加塔布",
    # ── 大西洋 / 印度洋 ──
    "Azores": "亚速尔群岛",
    "Bermuda": "百慕大",
    "Canary": "加那利群岛",
    "Cape_Verde": "佛得角",
    "Maldives": "马尔代夫",
    "Mauritius": "毛里求斯",
    "Reunion": "留尼汪",
    "Reykjavik": "雷克雅未克",
    "South_Georgia": "南乔治亚",
    "Stanley": "斯坦利",
    # ── 南极洲 ──
    "McMurdo": "麦克默多",
    "Palmer": "帕尔默",
    # ── 子区域（用于 America/Argentina/* 等多级时区） ──
    "Indiana": "印第安纳",
    "Kentucky": "肯塔基",
    "North_Dakota": "北达科他",
    "Indianapolis": "印第安纳波利斯",
    "Knox": "诺克斯",
    "Marengo": "马伦戈",
    "Petersburg": "彼得斯堡",
    "Tell_City": "特尔城",
    "Vevay": "维韦",
    "Vincennes": "文森斯",
    "Winamac": "威纳马克",
    "Monticello": "蒙蒂塞洛",
    "Beulah": "比尤拉",
    "Center": "森特",
    "New_Salem": "新塞勒姆",
    "Catamarca": "卡塔马卡",
    "Cordoba": "科尔多瓦",
    "Jujuy": "胡胡伊",
    "La_Rioja": "拉里奥哈",
    "Mendoza": "门多萨",
    "Rio_Gallegos": "里奥加耶戈斯",
    "Salta": "萨尔塔",
    "San_Juan": "圣胡安",
    "San_Luis": "圣路易斯",
    "Tucuman": "图库曼",
    "Ushuaia": "乌斯怀亚",
}
